# Generated by Django 5.1.2 on 2024-12-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='busyness',
        ),
        migrations.AlterField(
            model_name='jobs',
            name='type_of_job',
            field=models.CharField(choices=[('full_time', 'Полная занятость'), ('part_time', 'Частичная занятость'), ('remote', 'Удалённая работа'), ('freelance', 'Фриланс')], default='full_time', max_length=20, verbose_name='тип работы'),
        ),
    ]
