# Generated by Django 5.1.2 on 2024-12-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_jobs_type_of_job_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('active', 'активно ищу работу'), ('looking_for_offers', 'рассматриваю предложения'), ('disabled', 'не ищу')], default='active', max_length=20, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='о себе'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата рождения'),
        ),
    ]
