# Generated by Django 5.1.2 on 2024-12-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_userprofile_status_alter_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='salary',
            field=models.IntegerField(default=0, verbose_name='заработная плата'),
        ),
    ]
